import type { JobType, MatchedJob } from "./jobSearch";

export type FallbackJob = Omit<MatchedJob, "matchPercent" | "matchReasons">;

export const DOMAIN_FALLBACK_JOBS: Record<string, FallbackJob[]> = {
    "Mechanical Engineering": [
        {
            id: "job_mech_tata_motors",
            company: "Tata Motors",
            role: "Graduate Engineer Trainee - Mechanical",
            location: "Pune / Bangalore",
            type: "full-time",
            remote: false,
            tags: ["AutoCAD", "SolidWorks", "Manufacturing", "Automotive", "GD&T"],
            salaryRange: "₹6L–₹9L",
            description: "Join Tata Motors passenger & commercial vehicle engineering division. Work on chassis design, powertrain components, and vehicle manufacturing processes.",
            applyUrl: "https://www.tatamotors.com/careers/",
            postedAt: "2026-08-01",
            source: "ProInterview curated (Mechanical)",
        },
        {
            id: "job_mech_lt_design",
            company: "Larsen & Toubro (L&T)",
            role: "Mechanical Design Engineer",
            location: "Mumbai / Chennai",
            type: "full-time",
            remote: false,
            tags: ["ANSYS", "SolidWorks", "Piping", "Pressure Vessels", "FEA"],
            salaryRange: "₹7L–₹12L",
            description: "Design and analyze heavy engineering machinery, heat exchangers, and industrial systems. Perform finite element analysis and generate fabrication drawings.",
            applyUrl: "https://www.larsentoubro.com/corporate/careers/",
            postedAt: "2026-08-03",
            source: "ProInterview curated (Mechanical)",
        },
        {
            id: "job_mech_bosch_intern",
            company: "Bosch India",
            role: "Mechanical Engineering Intern",
            location: "Bangalore",
            type: "intern",
            remote: false,
            tags: ["CAD", "Production", "Manufacturing", "Quality Control"],
            salaryRange: "₹25k–₹40k / month Stipend",
            description: "Hands-on engineering internship assisting with manufacturing process optimization, tolerance stack-up analysis, and assembly line automation.",
            applyUrl: "https://careers.smartrecruiters.com/BoschGroup/india",
            postedAt: "2026-08-05",
            source: "ProInterview curated (Mechanical)",
        },
        {
            id: "job_mech_mahindra_prod",
            company: "Mahindra & Mahindra",
            role: "Production & Quality Engineer",
            location: "Pune / Nashik",
            type: "full-time",
            remote: false,
            tags: ["Manufacturing", "Six Sigma", "CNC", "Quality Assurance"],
            salaryRange: "₹6.5L–₹10L",
            description: "Oversee production lines, continuous improvement projects, and dimensional inspection of automotive assemblies using GD&T standards.",
            applyUrl: "https://jobs.mahindra.com/",
            postedAt: "2026-08-02",
            source: "ProInterview curated (Mechanical)",
        },
    ],
    "Civil Engineering": [
        {
            id: "job_civil_lt_site",
            company: "L&T Construction",
            role: "Civil Site Engineer",
            location: "Bangalore / Hyderabad / Delhi",
            type: "full-time",
            remote: false,
            tags: ["Site Supervision", "Concrete Technology", "AutoCAD", "Surveying"],
            salaryRange: "₹6L–₹9.5L",
            description: "Manage site execution, coordinate with subcontractors, verify bar bending schedules, and ensure construction quality and safety protocols.",
            applyUrl: "https://www.lntecc.com/careers/",
            postedAt: "2026-08-01",
            source: "ProInterview curated (Civil)",
        },
        {
            id: "job_civil_dlf_structural",
            company: "DLF India",
            role: "Structural Design Engineer",
            location: "Gurugram / Delhi NCR",
            type: "full-time",
            remote: false,
            tags: ["STAAD.Pro", "ETABS", "RCC Design", "Structural Analysis"],
            salaryRange: "₹7.5L–₹13L",
            description: "Perform structural analysis and design for high-rise residential and commercial towers using STAAD.Pro and ETABS in compliance with IS codes.",
            applyUrl: "https://www.dlf.in/careers",
            postedAt: "2026-08-02",
            source: "ProInterview curated (Civil)",
        },
        {
            id: "job_civil_shapoorji_intern",
            company: "Shapoorji Pallonji",
            role: "Civil Engineering Intern",
            location: "Mumbai / Bangalore",
            type: "intern",
            remote: false,
            tags: ["Quantity Surveying", "Site Execution", "Estimation", "AutoCAD"],
            salaryRange: "₹20k–₹35k / month Stipend",
            description: "Site internship covering quantity estimation, material reconciliation, quality checks on reinforcement, and daily progress reporting.",
            applyUrl: "https://www.shapoorjipallonji.com/careers",
            postedAt: "2026-08-04",
            source: "ProInterview curated (Civil)",
        },
    ],
    "Electrical Engineering": [
        {
            id: "job_elec_abb_systems",
            company: "ABB India",
            role: "Electrical Systems Engineer",
            location: "Bangalore",
            type: "full-time",
            remote: false,
            tags: ["Power Systems", "Switchgear", "Single Line Diagrams", "Transformers"],
            salaryRange: "₹7L–₹12L",
            description: "Design high and medium voltage electrical power distribution systems, select switchgear, and prepare engineering schematics.",
            applyUrl: "https://global.abb/group/en/careers",
            postedAt: "2026-08-01",
            source: "ProInterview curated (Electrical)",
        },
        {
            id: "job_elec_schneider_intern",
            company: "Schneider Electric",
            role: "Electrical Engineering Intern",
            location: "Bangalore / Chennai",
            type: "intern",
            remote: false,
            tags: ["PLC", "SCADA", "Automation", "Circuit Design"],
            salaryRange: "₹25k–₹40k / month Stipend",
            description: "Assist with electrical testing, PLC panel design, and energy management system configuration.",
            applyUrl: "https://www.se.com/in/en/about-us/careers/",
            postedAt: "2026-08-03",
            source: "ProInterview curated (Electrical)",
        },
    ],
    "Electronics & Embedded Systems": [
        {
            id: "job_embed_ti_engineer",
            company: "Texas Instruments",
            role: "Embedded Systems Engineer",
            location: "Bangalore",
            type: "full-time",
            remote: false,
            tags: ["Embedded C", "ARM Cortex", "RTOS", "Microcontrollers", "PCB"],
            salaryRange: "₹14L–₹22L",
            description: "Develop low-level device drivers, firmware for ARM microcontrollers, and real-time operating system applications.",
            applyUrl: "https://careers.ti.com/",
            postedAt: "2026-08-01",
            source: "ProInterview curated (Electronics)",
        },
        {
            id: "job_embed_bosch_firmware",
            company: "Bosch Global Software",
            role: "Firmware Engineer (0-2 Years / Trainee)",
            location: "Bangalore / Coimbatore",
            type: "full-time",
            remote: false,
            tags: ["Embedded C", "CAN Bus", "Microcontrollers", "Debugging"],
            salaryRange: "₹7L–₹11L",
            description: "Automotive electronic control unit (ECU) firmware development and testing using CANoe, C, and microcontroller hardware.",
            applyUrl: "https://www.bosch.in/careers/",
            postedAt: "2026-08-02",
            source: "ProInterview curated (Electronics)",
        },
        {
            id: "job_embed_qualcomm_intern",
            company: "Qualcomm India",
            role: "Hardware / Embedded Intern",
            location: "Hyderabad / Bangalore",
            type: "intern",
            remote: false,
            tags: ["Verilog", "Embedded C", "PCB Design", "Digital Design"],
            salaryRange: "₹50k–₹75k / month Stipend",
            description: "Internship working on wireless modem hardware testing, board bring-up, and embedded firmware verification.",
            applyUrl: "https://qualcomm.wd5.myworkdayjobs.com/External",
            postedAt: "2026-08-04",
            source: "ProInterview curated (Electronics)",
        },
    ],
    "Finance & Accounting": [
        {
            id: "job_fin_deloitte_analyst",
            company: "Deloitte India",
            role: "Financial Analyst",
            location: "Hyderabad / Mumbai / Bangalore",
            type: "full-time",
            remote: false,
            tags: ["Financial Modeling", "Excel", "Variance Analysis", "FP&A", "Forecasting"],
            salaryRange: "₹7L–₹12L",
            description: "Build financial models, perform budgeting and forecast variance analysis, and support client executive financial planning.",
            applyUrl: "https://jobsindia.deloitte.com/",
            postedAt: "2026-08-01",
            source: "ProInterview curated (Finance)",
        },
        {
            id: "job_fin_ey_audit",
            company: "EY (Ernst & Young)",
            role: "Audit & Tax Associate",
            location: "Bangalore / Delhi NCR / Mumbai",
            type: "full-time",
            remote: false,
            tags: ["Accounting", "GST", "Auditing", "Taxation", "Tally"],
            salaryRange: "₹5.5L–₹9L",
            description: "Perform statutory and internal audits, review financial statements under Indian GAAP/Ind AS, and compute tax liabilities.",
            applyUrl: "https://www.ey.com/en_in/careers",
            postedAt: "2026-08-02",
            source: "ProInterview curated (Finance)",
        },
        {
            id: "job_fin_hdfc_accounts",
            company: "HDFC Bank",
            role: "Accounts & Finance Executive",
            location: "Mumbai / Pune / Chennai",
            type: "full-time",
            remote: false,
            tags: ["Reconciliation", "General Ledger", "Tally Prime", "Excel"],
            salaryRange: "₹4.5L–₹7.5L",
            description: "Manage bank reconciliations, vendor ledger accounts, statutory filings, and monthly balance sheet preparation.",
            applyUrl: "https://www.hdfcbank.com/personal/about-us/careers",
            postedAt: "2026-08-04",
            source: "ProInterview curated (Finance)",
        },
        {
            id: "job_fin_kpmg_intern",
            company: "KPMG India",
            role: "Finance & Advisory Intern",
            location: "Bangalore / Gurgaon",
            type: "intern",
            remote: false,
            tags: ["Excel", "Financial Analysis", "Accounting", "Corporate Finance"],
            salaryRange: "₹20k–₹35k / month Stipend",
            description: "Assist advisory teams with industry research, financial data entry and cleanup, and quarterly financial review support.",
            applyUrl: "https://kpmg.com/in/en/home/careers.html",
            postedAt: "2026-08-05",
            source: "ProInterview curated (Finance)",
        },
    ],
    "Human Resources": [
        {
            id: "job_hr_wipro_executive",
            company: "Wipro",
            role: "HR Executive - Talent Acquisition",
            location: "Bangalore / Hyderabad",
            type: "full-time",
            remote: false,
            tags: ["Recruitment", "Sourcing", "Screening", "Interview Scheduling", "ATS"],
            salaryRange: "₹4.5L–₹7L",
            description: "Manage end-to-end recruitment lifecycle, source candidates through LinkedIn & Naukri, conduct HR screenings, and negotiate offers.",
            applyUrl: "https://careers.wipro.com/",
            postedAt: "2026-08-01",
            source: "ProInterview curated (HR)",
        },
        {
            id: "job_hr_reliance_ops",
            company: "Reliance Industries",
            role: "HR Operations Associate",
            location: "Mumbai",
            type: "full-time",
            remote: false,
            tags: ["Employee Onboarding", "Payroll", "HR Compliance", "Employee Relations"],
            salaryRange: "₹5L–₹8L",
            description: "Oversee employee onboarding, coordinate monthly payroll inputs, resolve employee queries, and ensure labor law compliance.",
            applyUrl: "https://careers.ril.com/",
            postedAt: "2026-08-03",
            source: "ProInterview curated (HR)",
        },
        {
            id: "job_hr_tata_intern",
            company: "Tata Consultancy Services",
            role: "Human Resources Intern",
            location: "Bangalore / Mumbai / Pune",
            type: "intern",
            remote: false,
            tags: ["Talent Acquisition", "Employee Engagement", "HR Policies", "Documentation"],
            salaryRange: "₹18k–₹30k / month Stipend",
            description: "Support the campus recruitment drive, candidate onboarding documentation, and employee engagement initiatives.",
            applyUrl: "https://www.tcs.com/careers",
            postedAt: "2026-08-04",
            source: "ProInterview curated (HR)",
        },
    ],
    "Marketing": [
        {
            id: "job_mkt_zomato_growth",
            company: "Zomato",
            role: "Digital Marketing Specialist",
            location: "Gurugram / Remote",
            type: "full-time",
            remote: true,
            tags: ["SEO", "Google Ads", "Meta Ads", "Performance Marketing", "Analytics"],
            salaryRange: "₹7L–₹12L",
            description: "Drive user acquisition through paid search, social media performance campaigns, and continuous landing page optimization.",
            applyUrl: "https://www.zomato.com/careers",
            postedAt: "2026-08-01",
            source: "ProInterview curated (Marketing)",
        },
        {
            id: "job_mkt_nykaa_content",
            company: "Nykaa",
            role: "Content & Social Media Specialist",
            location: "Mumbai",
            type: "full-time",
            remote: false,
            tags: ["Content Marketing", "Copywriting", "Social Media", "Brand Strategy"],
            salaryRange: "₹5L–₹8.5L",
            description: "Create engaging brand content across Instagram, YouTube, and email campaigns. Monitor engagement metrics and collaborate with influencers.",
            applyUrl: "https://www.nykaa.com/careers",
            postedAt: "2026-08-02",
            source: "ProInterview curated (Marketing)",
        },
        {
            id: "job_mkt_swiggy_intern",
            company: "Swiggy",
            role: "Marketing Intern",
            location: "Bangalore",
            type: "intern",
            remote: false,
            tags: ["SEO", "Market Research", "Social Media", "Campaigns"],
            salaryRange: "₹20k–₹35k / month Stipend",
            description: "Participate in local marketing activations, keyword research for organic growth, and competitive campaign benchmarking.",
            applyUrl: "https://careers.swiggy.com/",
            postedAt: "2026-08-04",
            source: "ProInterview curated (Marketing)",
        },
    ],
    "UI/UX & Product Design": [
        {
            id: "job_design_razorpay",
            company: "Razorpay",
            role: "Product Designer (UI/UX)",
            location: "Bangalore / Remote",
            type: "full-time",
            remote: true,
            tags: ["Figma", "Design Systems", "User Research", "Wireframing", "Prototyping"],
            salaryRange: "₹14L–₹24L",
            description: "Design intuitive payment and merchant banking workflows. Build scalable Figma design systems and conduct qualitative user usability tests.",
            applyUrl: "https://razorpay.com/jobs/",
            postedAt: "2026-08-01",
            source: "ProInterview curated (Design)",
        },
        {
            id: "job_design_swiggy_intern",
            company: "Swiggy",
            role: "UI/UX Design Intern",
            location: "Bangalore",
            type: "intern",
            remote: false,
            tags: ["Figma", "Interaction Design", "Visual Design", "Prototyping"],
            salaryRange: "₹35k–₹55k / month Stipend",
            description: "Work closely with senior product designers to craft customer delivery journey screens, interactive prototypes, and iconography.",
            applyUrl: "https://careers.swiggy.com/",
            postedAt: "2026-08-03",
            source: "ProInterview curated (Design)",
        },
    ],
    "Education & Teaching": [
        {
            id: "job_edu_unacademy_sme",
            company: "Unacademy",
            role: "Subject Matter Expert & Educator",
            location: "Bangalore / Remote",
            type: "full-time",
            remote: true,
            tags: ["Mathematics", "Curriculum Design", "Online Teaching", "Content Creation"],
            salaryRange: "₹5L–₹9L",
            description: "Design structured lesson plans, create engaging problem sets, and deliver live and recorded instructional modules for competitive exams.",
            applyUrl: "https://unacademy.com/careers",
            postedAt: "2026-08-01",
            source: "ProInterview curated (Education)",
        },
        {
            id: "job_edu_khan_tutor",
            company: "Khan Academy India",
            role: "Academic Content Coordinator",
            location: "New Delhi / Remote",
            type: "full-time",
            remote: true,
            tags: ["Pedagogy", "STEM Education", "Lesson Planning", "Assessment"],
            salaryRange: "₹6L–₹10L",
            description: "Develop localized educational curriculum, review instructional materials against national standards, and mentor learning coaches.",
            applyUrl: "https://www.khanacademy.org/careers",
            postedAt: "2026-08-02",
            source: "ProInterview curated (Education)",
        },
    ],
    "Healthcare": [
        {
            id: "job_health_apollo_officer",
            company: "Apollo Hospitals",
            role: "Resident Medical Officer / Clinical Specialist",
            location: "Hyderabad / Chennai / Bangalore",
            type: "full-time",
            remote: false,
            tags: ["Patient Care", "Clinical Diagnosis", "Emergency Care", "NABH Compliance"],
            salaryRange: "₹7.5L–₹14L",
            description: "Provide emergency and inpatient clinical care, perform patient evaluations, coordinate treatment plans, and ensure medical record accuracy.",
            applyUrl: "https://www.apollohospitals.com/careers/",
            postedAt: "2026-08-01",
            source: "ProInterview curated (Healthcare)",
        },
        {
            id: "job_health_fortis_ops",
            company: "Fortis Healthcare",
            role: "Healthcare Operations Coordinator",
            location: "Delhi NCR / Mumbai",
            type: "full-time",
            remote: false,
            tags: ["Hospital Administration", "Patient Services", "Quality Assurance"],
            salaryRange: "₹5L–₹8.5L",
            description: "Supervise outpatient department workflows, patient admission logistics, healthcare service standards, and hospital accreditation audits.",
            applyUrl: "https://www.fortishealthcare.com/careers",
            postedAt: "2026-08-03",
            source: "ProInterview curated (Healthcare)",
        },
    ],
    "General / Multidisciplinary": [
        {
            id: "job_gen_tata_mgmt",
            company: "Tata Business Excellence Group",
            role: "Management Trainee / Operations Associate",
            location: "Mumbai / Pune",
            type: "full-time",
            remote: false,
            tags: ["Operations", "Project Management", "MS Excel", "Communication"],
            salaryRange: "₹5L–₹8.5L",
            description: "Cross-functional management trainee role rotating through operations, vendor management, business process optimization, and executive reporting.",
            applyUrl: "https://www.tata.com/careers",
            postedAt: "2026-08-01",
            source: "ProInterview curated (General)",
        },
        {
            id: "job_gen_corp_intern",
            company: "Godrej Group",
            role: "Corporate Operations Intern",
            location: "Mumbai / Remote",
            type: "intern",
            remote: false,
            tags: ["Business Operations", "Research", "Documentation", "Coordination"],
            salaryRange: "₹20k–₹30k / month Stipend",
            description: "Support strategic project execution, data reporting, market benchmarking, and inter-departmental communications.",
            applyUrl: "https://www.godrej.com/careers",
            postedAt: "2026-08-04",
            source: "ProInterview curated (General)",
        },
    ],
};
